/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AudioStatus = { 'unmuted' : null } |
  { 'muted' : null };
export type ChatId = string;
export interface ChatMessage {
  'sender' : Principal,
  'message' : string,
  'timestamp' : bigint,
  'senderName' : string,
  'chatId' : ChatId,
}
export interface Participant {
  'id' : ParticipantId,
  'displayName' : string,
  'joinedAt' : Time,
  'isHost' : boolean,
  'videoStatus' : VideoStatus,
  'audioStatus' : AudioStatus,
}
export type ParticipantId = Principal;
export type RoomId = string;
export interface RoomRequest {
  'title' : string,
  'host' : Principal,
  'isPublic' : boolean,
}
export interface RoomView {
  'id' : RoomId,
  'title' : string,
  'participants' : Array<Participant>,
  'host' : ParticipantId,
  'createdAt' : Time,
  'isActive' : boolean,
  'isLocked' : boolean,
  'isPublic' : boolean,
}
export interface SignalingEvent {
  'sender' : Principal,
  'target' : Principal,
  'timestamp' : bigint,
  'payload' : string,
}
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile { 'displayName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VideoStatus = { 'on' : null } |
  { 'off' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSignalingEvent' : ActorMethod<[RoomId, Principal, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRoom' : ActorMethod<[RoomRequest], RoomId>,
  'endRoom' : ActorMethod<[RoomId], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLatestMessages' : ActorMethod<[RoomId], Array<ChatMessage>>,
  'getPublicRooms' : ActorMethod<[], Array<RoomView>>,
  'getRoomData' : ActorMethod<[string], [] | [RoomView]>,
  'getRoomParticipants' : ActorMethod<[RoomId], Array<Participant>>,
  'getRoomsByHost' : ActorMethod<[Principal], Array<RoomView>>,
  'getSignalingEvents' : ActorMethod<[RoomId], Array<SignalingEvent>>,
  'getUserById' : ActorMethod<[UserId], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileLegacy' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinRoom' : ActorMethod<[RoomId, string], boolean>,
  'kickParticipant' : ActorMethod<[RoomId, Principal], boolean>,
  'leaveRoom' : ActorMethod<[RoomId, Principal], boolean>,
  'lockRoom' : ActorMethod<[RoomId, boolean], boolean>,
  'muteAllParticipants' : ActorMethod<[RoomId], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[RoomId, string], boolean>,
  'setUserProfile' : ActorMethod<[string], boolean>,
  'toggleAudio' : ActorMethod<[RoomId], boolean>,
  'toggleVideo' : ActorMethod<[RoomId], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];