/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RoomRequest = IDL.Record({
  'title' : IDL.Text,
  'host' : IDL.Principal,
  'isPublic' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
export const ChatId = IDL.Text;
export const ChatMessage = IDL.Record({
  'sender' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
  'chatId' : ChatId,
});
export const ParticipantId = IDL.Principal;
export const Time = IDL.Int;
export const VideoStatus = IDL.Variant({ 'on' : IDL.Null, 'off' : IDL.Null });
export const AudioStatus = IDL.Variant({
  'unmuted' : IDL.Null,
  'muted' : IDL.Null,
});
export const Participant = IDL.Record({
  'id' : ParticipantId,
  'displayName' : IDL.Text,
  'joinedAt' : Time,
  'isHost' : IDL.Bool,
  'videoStatus' : VideoStatus,
  'audioStatus' : AudioStatus,
});
export const RoomView = IDL.Record({
  'id' : RoomId,
  'title' : IDL.Text,
  'participants' : IDL.Vec(Participant),
  'host' : ParticipantId,
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'isLocked' : IDL.Bool,
  'isPublic' : IDL.Bool,
});
export const SignalingEvent = IDL.Record({
  'sender' : IDL.Principal,
  'target' : IDL.Principal,
  'timestamp' : IDL.Int,
  'payload' : IDL.Text,
});
export const UserId = IDL.Principal;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSignalingEvent' : IDL.Func([RoomId, IDL.Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRoom' : IDL.Func([RoomRequest], [RoomId], []),
  'endRoom' : IDL.Func([RoomId], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLatestMessages' : IDL.Func([RoomId], [IDL.Vec(ChatMessage)], ['query']),
  'getPublicRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
  'getRoomData' : IDL.Func([IDL.Text], [IDL.Opt(RoomView)], ['query']),
  'getRoomParticipants' : IDL.Func([RoomId], [IDL.Vec(Participant)], ['query']),
  'getRoomsByHost' : IDL.Func([IDL.Principal], [IDL.Vec(RoomView)], ['query']),
  'getSignalingEvents' : IDL.Func(
      [RoomId],
      [IDL.Vec(SignalingEvent)],
      ['query'],
    ),
  'getUserById' : IDL.Func([UserId], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileLegacy' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinRoom' : IDL.Func([RoomId, IDL.Text], [IDL.Bool], []),
  'kickParticipant' : IDL.Func([RoomId, IDL.Principal], [IDL.Bool], []),
  'leaveRoom' : IDL.Func([RoomId, IDL.Principal], [IDL.Bool], []),
  'lockRoom' : IDL.Func([RoomId, IDL.Bool], [IDL.Bool], []),
  'muteAllParticipants' : IDL.Func([RoomId], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([RoomId, IDL.Text], [IDL.Bool], []),
  'setUserProfile' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'toggleAudio' : IDL.Func([RoomId], [IDL.Bool], []),
  'toggleVideo' : IDL.Func([RoomId], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RoomRequest = IDL.Record({
    'title' : IDL.Text,
    'host' : IDL.Principal,
    'isPublic' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
  const ChatId = IDL.Text;
  const ChatMessage = IDL.Record({
    'sender' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
    'chatId' : ChatId,
  });
  const ParticipantId = IDL.Principal;
  const Time = IDL.Int;
  const VideoStatus = IDL.Variant({ 'on' : IDL.Null, 'off' : IDL.Null });
  const AudioStatus = IDL.Variant({ 'unmuted' : IDL.Null, 'muted' : IDL.Null });
  const Participant = IDL.Record({
    'id' : ParticipantId,
    'displayName' : IDL.Text,
    'joinedAt' : Time,
    'isHost' : IDL.Bool,
    'videoStatus' : VideoStatus,
    'audioStatus' : AudioStatus,
  });
  const RoomView = IDL.Record({
    'id' : RoomId,
    'title' : IDL.Text,
    'participants' : IDL.Vec(Participant),
    'host' : ParticipantId,
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'isLocked' : IDL.Bool,
    'isPublic' : IDL.Bool,
  });
  const SignalingEvent = IDL.Record({
    'sender' : IDL.Principal,
    'target' : IDL.Principal,
    'timestamp' : IDL.Int,
    'payload' : IDL.Text,
  });
  const UserId = IDL.Principal;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSignalingEvent' : IDL.Func([RoomId, IDL.Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRoom' : IDL.Func([RoomRequest], [RoomId], []),
    'endRoom' : IDL.Func([RoomId], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLatestMessages' : IDL.Func([RoomId], [IDL.Vec(ChatMessage)], ['query']),
    'getPublicRooms' : IDL.Func([], [IDL.Vec(RoomView)], ['query']),
    'getRoomData' : IDL.Func([IDL.Text], [IDL.Opt(RoomView)], ['query']),
    'getRoomParticipants' : IDL.Func(
        [RoomId],
        [IDL.Vec(Participant)],
        ['query'],
      ),
    'getRoomsByHost' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(RoomView)],
        ['query'],
      ),
    'getSignalingEvents' : IDL.Func(
        [RoomId],
        [IDL.Vec(SignalingEvent)],
        ['query'],
      ),
    'getUserById' : IDL.Func([UserId], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileLegacy' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinRoom' : IDL.Func([RoomId, IDL.Text], [IDL.Bool], []),
    'kickParticipant' : IDL.Func([RoomId, IDL.Principal], [IDL.Bool], []),
    'leaveRoom' : IDL.Func([RoomId, IDL.Principal], [IDL.Bool], []),
    'lockRoom' : IDL.Func([RoomId, IDL.Bool], [IDL.Bool], []),
    'muteAllParticipants' : IDL.Func([RoomId], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([RoomId, IDL.Text], [IDL.Bool], []),
    'setUserProfile' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'toggleAudio' : IDL.Func([RoomId], [IDL.Bool], []),
    'toggleVideo' : IDL.Func([RoomId], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };