/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Participant {
    id: ParticipantId;
    displayName: string;
    joinedAt: Time;
    isHost: boolean;
    videoStatus: VideoStatus;
    audioStatus: AudioStatus;
}
export type Time = bigint;
export type ChatId = string;
export interface SignalingEvent {
    sender: Principal;
    target: Principal;
    timestamp: bigint;
    payload: string;
}
export type RoomId = string;
export type UserId = Principal;
export type ParticipantId = Principal;
export interface RoomRequest {
    title: string;
    host: Principal;
    isPublic: boolean;
}
export interface ChatMessage {
    sender: Principal;
    message: string;
    timestamp: bigint;
    senderName: string;
    chatId: ChatId;
}
export interface RoomView {
    id: RoomId;
    title: string;
    participants: Array<Participant>;
    host: ParticipantId;
    createdAt: Time;
    isActive: boolean;
    isLocked: boolean;
    isPublic: boolean;
}
export interface UserProfile {
    displayName: string;
}
export enum AudioStatus {
    unmuted = "unmuted",
    muted = "muted"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VideoStatus {
    on = "on",
    off = "off"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSignalingEvent(roomId: RoomId, target: Principal, payload: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createRoom(request: RoomRequest): Promise<RoomId>;
    endRoom(roomId: RoomId): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLatestMessages(roomId: RoomId): Promise<Array<ChatMessage>>;
    getPublicRooms(): Promise<Array<RoomView>>;
    getRoomData(roomId: string): Promise<RoomView | null>;
    getRoomParticipants(roomId: RoomId): Promise<Array<Participant>>;
    getRoomsByHost(hostId: Principal): Promise<Array<RoomView>>;
    getSignalingEvents(roomId: RoomId): Promise<Array<SignalingEvent>>;
    getUserById(userId: UserId): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProfileLegacy(): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    joinRoom(roomId: RoomId, displayName: string): Promise<boolean>;
    kickParticipant(roomId: RoomId, userId: Principal): Promise<boolean>;
    leaveRoom(roomId: RoomId, userId: Principal): Promise<boolean>;
    lockRoom(roomId: RoomId, locked: boolean): Promise<boolean>;
    muteAllParticipants(roomId: RoomId): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(roomId: RoomId, message: string): Promise<boolean>;
    setUserProfile(displayName: string): Promise<boolean>;
    toggleAudio(roomId: RoomId): Promise<boolean>;
    toggleVideo(roomId: RoomId): Promise<boolean>;
}
import type { AudioStatus as _AudioStatus, Participant as _Participant, ParticipantId as _ParticipantId, RoomId as _RoomId, RoomView as _RoomView, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VideoStatus as _VideoStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSignalingEvent(arg0: RoomId, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSignalingEvent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSignalingEvent(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createRoom(arg0: RoomRequest): Promise<RoomId> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoom(arg0);
            return result;
        }
    }
    async endRoom(arg0: RoomId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.endRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endRoom(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestMessages(arg0: RoomId): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestMessages(arg0);
            return result;
        }
    }
    async getPublicRooms(): Promise<Array<RoomView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicRooms();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicRooms();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomData(arg0: string): Promise<RoomView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomData(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomData(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomParticipants(arg0: RoomId): Promise<Array<Participant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomParticipants(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomParticipants(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomsByHost(arg0: Principal): Promise<Array<RoomView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomsByHost(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomsByHost(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSignalingEvents(arg0: RoomId): Promise<Array<SignalingEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignalingEvents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignalingEvents(arg0);
            return result;
        }
    }
    async getUserById(arg0: UserId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileLegacy(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileLegacy();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileLegacy();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinRoom(arg0: RoomId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.joinRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinRoom(arg0, arg1);
            return result;
        }
    }
    async kickParticipant(arg0: RoomId, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.kickParticipant(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.kickParticipant(arg0, arg1);
            return result;
        }
    }
    async leaveRoom(arg0: RoomId, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveRoom(arg0, arg1);
            return result;
        }
    }
    async lockRoom(arg0: RoomId, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.lockRoom(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lockRoom(arg0, arg1);
            return result;
        }
    }
    async muteAllParticipants(arg0: RoomId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.muteAllParticipants(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.muteAllParticipants(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendMessage(arg0: RoomId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async setUserProfile(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserProfile(arg0);
            return result;
        }
    }
    async toggleAudio(arg0: RoomId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAudio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAudio(arg0);
            return result;
        }
    }
    async toggleVideo(arg0: RoomId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleVideo(arg0);
            return result;
        }
    }
}
function from_candid_AudioStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioStatus): AudioStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Participant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Participant): Participant {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_RoomView_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomView): RoomView {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_VideoStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoStatus): VideoStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RoomView]): RoomView | null {
    return value.length === 0 ? null : from_candid_RoomView_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ParticipantId;
    displayName: string;
    joinedAt: _Time;
    isHost: boolean;
    videoStatus: _VideoStatus;
    audioStatus: _AudioStatus;
}): {
    id: ParticipantId;
    displayName: string;
    joinedAt: Time;
    isHost: boolean;
    videoStatus: VideoStatus;
    audioStatus: AudioStatus;
} {
    return {
        id: value.id,
        displayName: value.displayName,
        joinedAt: value.joinedAt,
        isHost: value.isHost,
        videoStatus: from_candid_VideoStatus_n12(_uploadFile, _downloadFile, value.videoStatus),
        audioStatus: from_candid_AudioStatus_n14(_uploadFile, _downloadFile, value.audioStatus)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RoomId;
    title: string;
    participants: Array<_Participant>;
    host: _ParticipantId;
    createdAt: _Time;
    isActive: boolean;
    isLocked: boolean;
    isPublic: boolean;
}): {
    id: RoomId;
    title: string;
    participants: Array<Participant>;
    host: ParticipantId;
    createdAt: Time;
    isActive: boolean;
    isLocked: boolean;
    isPublic: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        participants: from_candid_vec_n9(_uploadFile, _downloadFile, value.participants),
        host: value.host,
        createdAt: value.createdAt,
        isActive: value.isActive,
        isLocked: value.isLocked,
        isPublic: value.isPublic
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    on: null;
} | {
    off: null;
}): VideoStatus {
    return "on" in value ? VideoStatus.on : "off" in value ? VideoStatus.off : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unmuted: null;
} | {
    muted: null;
}): AudioStatus {
    return "unmuted" in value ? AudioStatus.unmuted : "muted" in value ? AudioStatus.muted : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoomView>): Array<RoomView> {
    return value.map((x)=>from_candid_RoomView_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Participant>): Array<Participant> {
    return value.map((x)=>from_candid_Participant_n10(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
